config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'surf_sessions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :surf_sessions
  get "archives", to: "surf_sessions#archives"

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

   # The user giving the follow
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  # The user being followed
  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/surf_session.rb
class SurfSession < ApplicationRecord
  belongs_to :user
  has_many_attached :photos

  validates :spot, :description, :date, :rating, :spot_type, :tide, presence: true
  scope :from_year, ->(date) { where(date: date.beginning_of_year..date.end_of_year) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sessions, foreign_key: 'user_id'

  has_one_attached :photo

  # Will return an array of follows for the given user instance
  has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

  # Will return an array of users who follow the user instance
  has_many :followers, through: :received_follows, source: :follower

  # returns an array of follows a user gave to someone else
  has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"

  # returns an array of other users who the user has followed
  has_many :followings, through: :given_follows, source: :followed_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # def after_sign_in_path_for(resource)
  #   #binding.pry
  #   user_path(current_user) # your path
  # end

  before_action :set_user

    private

  def set_user
    @user = current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

end

app/controllers/surf_sessions_controller.rb
class SurfSessionsController < ApplicationController
  include Pagy::Backend
  before_action :set_surf_session, except: [:index, :archives, :new, :create]
  before_action :set_user
  before_action :set_all_surf_sessions, only: [:index, :archives]

  def index
    @navbar_style = :logo_menu
    @current_year_surf_sessions = @surf_sessions.from_year(Time.now)
    @last_surf_sessions = @current_year_surf_sessions.first(3)
    @spots_count = @current_year_surf_sessions.pluck(:spot).uniq.size
    @users = User.all
  end

  def archives
    @pagy, @archived_surf_sessions = pagy(@surf_sessions, items: 10)
    @navbar_style = :logo_menu

  end

  def show
  end

  def new
    @navbar_style = :logo_back
    @surf_session = SurfSession.new
  end

  def create
    @surf_session = SurfSession.new(ss_params)
    @surf_session.user = @user

    if @surf_session.valid?
      @surf_session.save
      redirect_to surf_sessions_path
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def edit
  end

  def update
    @surf_session.update(ss_params)
    redirect_to surf_sessions_path(@surf_session)
  end

  def destroy
    @surf_session.destroy
    redirect_to surf_sessions_path(@surf_session)
  end

  private

  def set_surf_session
    @surf_session = SurfSession.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def ss_params
    params.require(:surf_session).permit(:title, :spot, :description, :date, :spot_type, :tide, :wave, :wind, :rating, photos: [])
  end

  def set_all_surf_sessions
    @surf_sessions = SurfSession.where(user_id: @user).order('date DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def tide(surf_session_tide)
    case surf_session_tide
    when "high-tide"
      image_tag 'high-tide.png', width: 35
    when "mid-tide"
      image_tag 'mid-tide.png', width: 35
    when "low-tide"
      image_tag "low-tide.png", width: 35
    end
  end

  def spot_type(surf_session_spot_type)
    case surf_session_spot_type
    when "reef"
      image_tag 'reef.png', width: 35
    when "beach"
      image_tag 'beach.png', width: 35
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySurfLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

    <%= render 'shared/navbar' if current_user.present? %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logoMSB.png" %>
  <% end %>

  <div class="nav-action">

  <!--  SUR TOUTES PAGES -->


   <!--  SI PAGE ACTUEL == INDEX -> LOGO menu-->
    <% if @navbar_style == :logo_menu %>
      <%= link_to new_surf_session_path, class: "icon navbar-brand action-icon" do %>
        <%= image_tag "add.png", data: { turbolinks: false } %>
      <% end %>
      <%= image_tag "menu.png", class: "nav-menu" %>
      <div class="show-menu show-click">
        <%= link_to "Log out", destroy_user_session_path, method: :delete  %>
        <%= link_to "My profile", edit_user_registration_path, method: :get  %>
      </div>

    <!--  SI PAGE ACTUEL == NEW -> LOGO back-->
    <% elsif @navbar_style == :logo_back %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "back.png" %>
      <% end %>

    <!--  SINON PAGE ACTUEL == SHOW -> LOGO share + insertion FB et WA-->
    <% elsif current_page?(surf_session_path(@surf_session)) %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "back.png" %>
      <% end %>
      <%= image_tag "share.png", class: "nav-share" %>
      <div class="share-menu show-click">
        <div class="share">
          <div class="fb-share-button" data-href= "<%= request.url  %>" data-layout="button" data-size="large">
            <a target="_blank"
              href="https://www.facebook.com/sharer/sharer.php?u=<%=request.url%>%2F&amp;src=sdkpreparse"
              class="fb-xfbml-parse-ignore">Share on FB</a>
          </div>
            <a class="WA" href="whatsapp://send?text=<%= request.url %>">WhatsApp</a>
        </div>
      </div>

    <% end %>

  </div>
</div>

app/views/surf_sessions/_form.html.erb
<div class="form-container">
  <!-- <div class="row"> -->
   <!--  <div class="col-xs-1">
 -->
 <!-- how to access to current user name ??
      < @current_user.name.capitalize %> - -->
      <!--  how to access to current user name ??
        < @surf_sessions.count +1 %> - -->
         <h3>
         <% if @current_user.name %>
          <%= @current_user.name.capitalize %>
          <% else %>
          <%= @current_user.email %>
          <% end %>

          - Let's register a new session
          </h3>



      <%= simple_form_for(surf_session) do |f| %>

        <%= f.input :spot, label:"Spot" %>
        <%= f.input :wind, label:"Wind direction" %>
        <%= f.input :wave, label:"Waves" %>

        <div class="spot-selector">
          <label>Spot type</label>
          <input id="beach" type="radio" name="surf_session[spot_type]" value="beach" <%= "checked" if surf_session.spot_type == "beach" %> />
          <label label="surf_session[spot_type]" class="spottype beach" for="beach" ></label>
          <input id="reef" type="radio" name="surf_session[spot_type]" value="reef" <%= "checked" if surf_session.spot_type == "reef" %>/>
          <label label="surf_session[spot_type]" class="spottype reef" for="reef"></label>
        </div>

        <div class="tide-selector">
          <label>Tide</label>
          <input id="high-tide" type="radio" name="surf_session[tide]" value="high-tide" <%= "checked" if surf_session.tide == "high-tide" %> />
          <label label="surf_session[tide]" class="tide high-tide" for="high-tide"></label>
          <input id="mid-tide" type="radio" name="surf_session[tide]" value="mid-tide" <%= "checked" if surf_session.tide == "mid-tide" %> />
          <label label="surf_session[tide]" class="tide mid-tide"for="mid-tide"></label>
          <input id="low-tide" type="radio" name="surf_session[tide]" value="low-tide" <%= "checked" if surf_session.tide == "low-tide" %> />
          <label label="surf_session[tide]" class="tide low-tide"for="low-tide"></label>
        </div>

        <div class="info-session">
          <%= f.input :date, as: :string, type: :text, input_html: {class: 'flatpickr'} %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your sesh'" %>
          <%= f.input :description %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>

         <!-- CAMERA ACCESS ?! -->
         <!-- <input type="file" name="uploadedfile" accept="image/*" capture="camera">
 -->

          <%= f.button :submit, "Save", class: "btn-flat save" %>
        </div>
      <% end %>
    <!-- </div> -->
 <!--  </div> -->
</div>

app/views/surf_sessions/_surf_session_card.html.erb
<div class="session-card">
  <div class="index-photo">
    <% if surf_session.photos.any? %>
      <%= cl_image_tag surf_session.photos.first.key  %>
      <% else %>
      <%= image_tag "chargepic.png"  %>
    <% end %>
  </div>
  <div class="index-session">
    <%= link_to surf_session.spot, surf_session_path(surf_session)%>
    <%= link_to surf_session.date.strftime("%d %B %Y"), surf_session_path(surf_session) %>
    <%= link_to (image_tag "trash.png", width:"20px"), surf_session_path(surf_session), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/surf_sessions/archives.html.erb
<div class="archives-container">
  <div class="home-title">
      <h2>Archives</h2>
  </div>

  <div class= "session-cards" data-controller="hello">
    <div class="pagination">
      <h3>Previous sessions</h3>
      <h3><%== pagy_nav(@pagy) %></h3>
    </div>
    <% @archived_surf_sessions.each do |surf_session| %>
      <%= render "surf_sessions/surf_session_card", surf_session: surf_session  %>
    <% end %>
  </div>
</div>

app/views/surf_sessions/edit.html.erb
<%= render 'surf_sessions/form', surf_session: @surf_session %>

app/views/surf_sessions/index.html.erb
<div class="home-banner">
    <h1>MYSURF<span>LOG</span></h1>
</div>
  <div class="home-logged">
    <% if @surf_sessions.size == 0 %>
      <div class="home-title-no-session">
          <h2>Start here &#x2935;  </h2>
          <%= link_to "Add my first session !", new_surf_session_path, class: "btn" %>
      </div>
      <% else %>
        <div class="home-title">
            <h2><%= Time.now.strftime("%Y") %>, <%= @current_year_surf_sessions.size %> sessions so far</h2>
            <h3>and you surfed <%= @spots_count  %> different spots!</h3>
        </div>
    <div class= "session-cards">
      <% @last_surf_sessions.each do |surf_session| %>
        <%= render "surf_sessions/surf_session_card", surf_session: surf_session  %>
      <% end %>
    </div>
      <%= link_to "View all", archives_path, class: "btn view-btn" %>
    <% end %>
  </div>

app/views/surf_sessions/new.html.erb
 <%= render 'surf_sessions/form', surf_session: @surf_session%>

app/views/surf_sessions/show.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v11.0" nonce="A5KZD3zX"></script>

<div class="container session-container show">
  <h1><%= @surf_session.title %></h1>
  <h2><%= @surf_session.spot %></h2>

  <div class="show-photos">
    <% if @surf_session.photos.exists? && (@surf_session.photos.count > 1) %>
      <div data-controller="carousel" class="swiper-container">
        <div class="swiper-wrapper">
          <% @surf_session.photos.each do |photo| %>
            <div class="swiper-slide">
              <%= cl_image_tag photo.key, crop: :fill, class:"d-block w-100" %>
            </div>
          <% end %>
        </div>
      </div>
    <% elsif @surf_session.photos.exists? %>
      <% @surf_session.photos.each do |photo| %>
         <%= cl_image_tag photo.key, crop: :fill %>
      <% end %>
    <% end %>
  </div>

  <div class="about-spot">
    <div class="stars">
      <p><% @surf_session.rating.times do |rating| %>
      <%= image_tag "stars.svg", width:30, height:30 %>
      <% end %></p>
    </div>
        <h3><label>About the spot</label></h3>
    <div class="picto">
      <div class="picto1">
        <div> <%= spot_type(@surf_session.spot_type) %> <%= @surf_session.spot_type %> </div>
        <div> <%= tide(@surf_session.tide) %> <%= @surf_session.tide %> </div>
      </div>
      <div class="picto2">
        <p><%= image_tag "wind.png", width:35 %> <%= @surf_session.wind %></p>
        <p><%= image_tag "wave.png", width:35 %> <%= @surf_session.wave %></p>
      </div>
    </div>
  </div>


  <div class='about-session'>
    <p><%= @surf_session.date.strftime("%A %d %B") %></p>
    <p><%= @surf_session.description %></p>
  </div>


  <div class="buttons">
    <button class="btn-flat"><%= link_to "Edit", edit_surf_session_path(@surf_session), data: { turbolinks: false } %> </button>
    <button class="btn-flat"><%= link_to "Delete", @surf_session, method: :delete, data: { confirm: "Are you sure ?" } %></button>

  </div>
</div>

app/views/users/show.html.erb
<%= @user.email %>